namespace IGCLWrapper
{
    public enum _ctl_display_setting_content_type_t
    {
        CTL_DISPLAY_SETTING_CONTENT_TYPE_DEFAULT = 0,
        CTL_DISPLAY_SETTING_CONTENT_TYPE_DISABLED = 1,
        CTL_DISPLAY_SETTING_CONTENT_TYPE_DESKTOP = 2,
        CTL_DISPLAY_SETTING_CONTENT_TYPE_MEDIA = 3,
        CTL_DISPLAY_SETTING_CONTENT_TYPE_GAMING = 4,
        CTL_DISPLAY_SETTING_CONTENT_TYPE_MAX,
    }
}
