namespace IGCLWrapper
{
    public enum _ctl_video_processing_feature_t
    {
        CTL_VIDEO_PROCESSING_FEATURE_FILM_MODE_DETECTION = 0,
        CTL_VIDEO_PROCESSING_FEATURE_NOISE_REDUCTION = 1,
        CTL_VIDEO_PROCESSING_FEATURE_SHARPNESS = 2,
        CTL_VIDEO_PROCESSING_FEATURE_ADAPTIVE_CONTRAST_ENHANCEMENT = 3,
        CTL_VIDEO_PROCESSING_FEATURE_SUPER_RESOLUTION = 4,
        CTL_VIDEO_PROCESSING_FEATURE_STANDARD_COLOR_CORRECTION = 5,
        CTL_VIDEO_PROCESSING_FEATURE_TOTAL_COLOR_CORRECTION = 6,
        CTL_VIDEO_PROCESSING_FEATURE_SKIN_TONE_ENHANCEMENT = 7,
        CTL_VIDEO_PROCESSING_FEATURE_MAX,
    }
}
