namespace IGCLWrapper
{
    public enum _ctl_units_t
    {
        CTL_UNITS_FREQUENCY_MHZ = 0,
        CTL_UNITS_OPERATIONS_GTS = 1,
        CTL_UNITS_OPERATIONS_MTS = 2,
        CTL_UNITS_VOLTAGE_VOLTS = 3,
        CTL_UNITS_POWER_WATTS = 4,
        CTL_UNITS_TEMPERATURE_CELSIUS = 5,
        CTL_UNITS_ENERGY_JOULES = 6,
        CTL_UNITS_TIME_SECONDS = 7,
        CTL_UNITS_MEMORY_BYTES = 8,
        CTL_UNITS_ANGULAR_SPEED_RPM = 9,
        CTL_UNITS_POWER_MILLIWATTS = 10,
        CTL_UNITS_PERCENT = 11,
        CTL_UNITS_MEM_SPEED_GBPS = 12,
        CTL_UNITS_VOLTAGE_MILLIVOLTS = 13,
        CTL_UNITS_BANDWIDTH_MBPS = 14,
        CTL_UNITS_UNKNOWN = 0x4800FFFF,
        CTL_UNITS_MAX,
    }
}
