namespace IGCLWrapper
{
    public enum _ctl_video_processing_super_resolution_flag_t
    {
        CTL_VIDEO_PROCESSING_SUPER_RESOLUTION_FLAG_DISABLE = (1 << 0),
        CTL_VIDEO_PROCESSING_SUPER_RESOLUTION_FLAG_ENABLE_DEFAULT_SCENARIO_MODE = (1 << 1),
        CTL_VIDEO_PROCESSING_SUPER_RESOLUTION_FLAG_ENABLE_CONFERENCE_SCENARIO_MODE = (1 << 2),
        CTL_VIDEO_PROCESSING_SUPER_RESOLUTION_FLAG_ENABLE_CAMERA_SCENARIO_MODE = (1 << 3),
        CTL_VIDEO_PROCESSING_SUPER_RESOLUTION_FLAG_MAX = unchecked((int)(0x80000000)),
    }
}
