namespace IGCLWrapper
{
    public enum ctl_custom_mode_operation_types_t
    {
        CTL_CUSTOM_MODE_OPERATION_TYPES_GET_CUSTOM_SOURCE_MODES = 0,
        CTL_CUSTOM_MODE_OPERATION_TYPES_ADD_CUSTOM_SOURCE_MODE = 1,
        CTL_CUSTOM_MODE_OPERATION_TYPES_REMOVE_CUSTOM_SOURCE_MODES = 2,
        CTL_CUSTOM_MODE_OPERATION_TYPES_MAX,
    }
}
