namespace IGCLWrapper
{
    public enum ctl_pixtx_gamma_encoding_type_t
    {
        CTL_PIXTX_GAMMA_ENCODING_TYPE_SRGB = 0,
        CTL_PIXTX_GAMMA_ENCODING_TYPE_REC709 = 1,
        CTL_PIXTX_GAMMA_ENCODING_TYPE_ST2084 = 2,
        CTL_PIXTX_GAMMA_ENCODING_TYPE_HLG = 3,
        CTL_PIXTX_GAMMA_ENCODING_TYPE_LINEAR = 4,
        CTL_PIXTX_GAMMA_ENCODING_TYPE_MAX,
    }
}
