namespace IGCLWrapper
{
    public enum ctl_3d_frame_pacing_types_t
    {
        CTL_3D_FRAME_PACING_TYPES_DISABLE = 0,
        CTL_3D_FRAME_PACING_TYPES_ENABLE_MODE_FRAME_NO_SMOOTHENING = 1,
        CTL_3D_FRAME_PACING_TYPES_ENABLE_MODE_FRAME_MAX_SMOOTHENING = 2,
        CTL_3D_FRAME_PACING_TYPES_ENABLE_MODE_COMPETITIVE_GAMING = 3,
        CTL_3D_FRAME_PACING_TYPES_MAX,
    }
}
