namespace IGCLWrapper
{
    public enum ctl_freq_throttle_reason_flag_t
    {
        CTL_FREQ_THROTTLE_REASON_FLAG_AVE_PWR_CAP = (1 << 0),
        CTL_FREQ_THROTTLE_REASON_FLAG_BURST_PWR_CAP = (1 << 1),
        CTL_FREQ_THROTTLE_REASON_FLAG_CURRENT_LIMIT = (1 << 2),
        CTL_FREQ_THROTTLE_REASON_FLAG_THERMAL_LIMIT = (1 << 3),
        CTL_FREQ_THROTTLE_REASON_FLAG_PSU_ALERT = (1 << 4),
        CTL_FREQ_THROTTLE_REASON_FLAG_SW_RANGE = (1 << 5),
        CTL_FREQ_THROTTLE_REASON_FLAG_HW_RANGE = (1 << 6),
        CTL_FREQ_THROTTLE_REASON_FLAG_MAX = unchecked((int)(0x80000000)),
    }
}
