namespace IGCLWrapper
{
    public enum ctl_combined_display_optype_t
    {
        CTL_COMBINED_DISPLAY_OPTYPE_IS_SUPPORTED_CONFIG = 1,
        CTL_COMBINED_DISPLAY_OPTYPE_ENABLE = 2,
        CTL_COMBINED_DISPLAY_OPTYPE_DISABLE = 3,
        CTL_COMBINED_DISPLAY_OPTYPE_QUERY_CONFIG = 4,
        CTL_COMBINED_DISPLAY_OPTYPE_MAX,
    }
}
