namespace IGCLWrapper
{
    public enum ctl_edid_management_optype_t
    {
        CTL_EDID_MANAGEMENT_OPTYPE_READ_EDID = 1,
        CTL_EDID_MANAGEMENT_OPTYPE_LOCK_EDID = 2,
        CTL_EDID_MANAGEMENT_OPTYPE_UNLOCK_EDID = 3,
        CTL_EDID_MANAGEMENT_OPTYPE_OVERRIDE_EDID = 4,
        CTL_EDID_MANAGEMENT_OPTYPE_UNDO_OVERRIDE_EDID = 5,
        CTL_EDID_MANAGEMENT_OPTYPE_MAX,
    }
}
