//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ADLX_SSM_BIAS_MODE {
  SSM_BIAS_AUTO = 0,
  SSM_BIAS_MANUAL
}
