//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ADLX_PCI_BUS_TYPE {
  UNDEFINED = 0,
  PCI,
  AGP,
  PCIE,
  PCIE_2_0,
  PCIE_3_0,
  PCIE_4_0
}
