//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum ADLX_DP_LINK_RATE {
  DP_LINK_RATE_UNKNOWN = 0,
  DP_LINK_RATE_RBR,
  DP_LINK_RATE_2_16GBPS,
  DP_LINK_RATE_2_43GBPS,
  DP_LINK_RATE_HBR,
  DP_LINK_RATE_4_32GBPS,
  DP_LINK_RATE_HBR2,
  DP_LINK_RATE_HBR3,
  DP_LINK_RATE_UHBR10,
  DP_LINK_RATE_UHBR13D5,
  DP_LINK_RATE_UHBR20
}
