//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXGPUAutoTuning : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXGPUAutoTuning(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXGPUAutoTuning_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXGPUAutoTuning obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXGPUAutoTuning obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXGPUAutoTuning(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXGPUAutoTuning_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedUndervoltGPU(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUAutoTuning_IsSupportedUndervoltGPU(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedOverclockGPU(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUAutoTuning_IsSupportedOverclockGPU(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedOverclockVRAM(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUAutoTuning_IsSupportedOverclockVRAM(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT IsCurrentUndervoltGPU(SWIGTYPE_p_bool isUndervoltGPU) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUAutoTuning_IsCurrentUndervoltGPU(swigCPtr, SWIGTYPE_p_bool.getCPtr(isUndervoltGPU));
    return ret;
  }

  public virtual ADLX_RESULT IsCurrentOverclockGPU(SWIGTYPE_p_bool isOverclockGPU) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUAutoTuning_IsCurrentOverclockGPU(swigCPtr, SWIGTYPE_p_bool.getCPtr(isOverclockGPU));
    return ret;
  }

  public virtual ADLX_RESULT IsCurrentOverclockVRAM(SWIGTYPE_p_bool isOverclockVRAM) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUAutoTuning_IsCurrentOverclockVRAM(swigCPtr, SWIGTYPE_p_bool.getCPtr(isOverclockVRAM));
    return ret;
  }

  public virtual ADLX_RESULT StartUndervoltGPU(IADLXGPUAutoTuningCompleteListener pCompleteListener) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUAutoTuning_StartUndervoltGPU(swigCPtr, IADLXGPUAutoTuningCompleteListener.getCPtr(pCompleteListener));
    return ret;
  }

  public virtual ADLX_RESULT StartOverclockGPU(IADLXGPUAutoTuningCompleteListener pCompleteListener) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUAutoTuning_StartOverclockGPU(swigCPtr, IADLXGPUAutoTuningCompleteListener.getCPtr(pCompleteListener));
    return ret;
  }

  public virtual ADLX_RESULT StartOverclockVRAM(IADLXGPUAutoTuningCompleteListener pCompleteListener) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPUAutoTuning_StartOverclockVRAM(swigCPtr, IADLXGPUAutoTuningCompleteListener.getCPtr(pCompleteListener));
    return ret;
  }

}
