//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXDisplayVariBright1 : IADLXDisplayVariBright {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXDisplayVariBright1(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXDisplayVariBright1_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXDisplayVariBright1 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXDisplayVariBright1 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXDisplayVariBright1(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXDisplayVariBright1_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsBacklightAdaptiveSupported(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_IsBacklightAdaptiveSupported(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT IsBacklightAdaptiveEnabled(SWIGTYPE_p_bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_IsBacklightAdaptiveEnabled(swigCPtr, SWIGTYPE_p_bool.getCPtr(enabled));
    return ret;
  }

  public virtual ADLX_RESULT SetBacklightAdaptiveEnabled(bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_SetBacklightAdaptiveEnabled(swigCPtr, enabled);
    return ret;
  }

  public virtual ADLX_RESULT IsBatteryLifeSupported(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_IsBatteryLifeSupported(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT IsBatteryLifeEnabled(SWIGTYPE_p_bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_IsBatteryLifeEnabled(swigCPtr, SWIGTYPE_p_bool.getCPtr(enabled));
    return ret;
  }

  public virtual ADLX_RESULT SetBatteryLifeEnabled(bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_SetBatteryLifeEnabled(swigCPtr, enabled);
    return ret;
  }

  public virtual ADLX_RESULT IsWindowsPowerModeSupported(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_IsWindowsPowerModeSupported(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT IsWindowsPowerModeEnabled(SWIGTYPE_p_bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_IsWindowsPowerModeEnabled(swigCPtr, SWIGTYPE_p_bool.getCPtr(enabled));
    return ret;
  }

  public virtual ADLX_RESULT SetWindowsPowerModeEnabled(bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_SetWindowsPowerModeEnabled(swigCPtr, enabled);
    return ret;
  }

  public virtual ADLX_RESULT IsFullScreenVideoSupported(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_IsFullScreenVideoSupported(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT IsFullScreenVideoEnabled(SWIGTYPE_p_bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_IsFullScreenVideoEnabled(swigCPtr, SWIGTYPE_p_bool.getCPtr(enabled));
    return ret;
  }

  public virtual ADLX_RESULT SetFullScreenVideoEnabled(bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayVariBright1_SetFullScreenVideoEnabled(swigCPtr, enabled);
    return ret;
  }

}
