//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXGPU1 : IADLXGPU {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXGPU1(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXGPU1_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXGPU1 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXGPU1 obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXGPU1(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXGPU1_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT PCIBusType(SWIGTYPE_p_ADLX_PCI_BUS_TYPE busType) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU1_PCIBusType(swigCPtr, SWIGTYPE_p_ADLX_PCI_BUS_TYPE.getCPtr(busType));
    return ret;
  }

  public virtual ADLX_RESULT PCIBusLaneWidth(SWIGTYPE_p_unsigned_int laneWidth) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU1_PCIBusLaneWidth(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(laneWidth));
    return ret;
  }

  public virtual ADLX_RESULT MultiGPUMode(SWIGTYPE_p_ADLX_MGPU_MODE mode) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU1_MultiGPUMode(swigCPtr, SWIGTYPE_p_ADLX_MGPU_MODE.getCPtr(mode));
    return ret;
  }

  public virtual ADLX_RESULT ProductName(SWIGTYPE_p_p_char productName) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXGPU1_ProductName(swigCPtr, SWIGTYPE_p_p_char.getCPtr(productName));
    return ret;
  }

}
