//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXDisplayPixelFormat : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXDisplayPixelFormat(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXDisplayPixelFormat_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXDisplayPixelFormat obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXDisplayPixelFormat obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXDisplayPixelFormat(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXDisplayPixelFormat_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsSupported(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayPixelFormat_IsSupported(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT GetValue(SWIGTYPE_p_ADLX_PIXEL_FORMAT pixelFormat) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayPixelFormat_GetValue(swigCPtr, SWIGTYPE_p_ADLX_PIXEL_FORMAT.getCPtr(pixelFormat));
    return ret;
  }

  public virtual ADLX_RESULT SetValue(ADLX_PIXEL_FORMAT pixelFormat) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayPixelFormat_SetValue(swigCPtr, (int)pixelFormat);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedPixelFormat(ADLX_PIXEL_FORMAT pixelFormat, SWIGTYPE_p_bool supportd) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayPixelFormat_IsSupportedPixelFormat(swigCPtr, (int)pixelFormat, SWIGTYPE_p_bool.getCPtr(supportd));
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedRGB444Full(SWIGTYPE_p_bool supportd) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayPixelFormat_IsSupportedRGB444Full(swigCPtr, SWIGTYPE_p_bool.getCPtr(supportd));
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedYCbCr444(SWIGTYPE_p_bool supportd) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayPixelFormat_IsSupportedYCbCr444(swigCPtr, SWIGTYPE_p_bool.getCPtr(supportd));
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedYCbCr422(SWIGTYPE_p_bool supportd) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayPixelFormat_IsSupportedYCbCr422(swigCPtr, SWIGTYPE_p_bool.getCPtr(supportd));
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedRGB444Limited(SWIGTYPE_p_bool supportd) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayPixelFormat_IsSupportedRGB444Limited(swigCPtr, SWIGTYPE_p_bool.getCPtr(supportd));
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedYCbCr420(SWIGTYPE_p_bool supportd) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayPixelFormat_IsSupportedYCbCr420(swigCPtr, SWIGTYPE_p_bool.getCPtr(supportd));
    return ret;
  }

}
