//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXApplication : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXApplication(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXApplication_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXApplication obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXApplication obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXApplication(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXApplication_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT ProcessID(SWIGTYPE_p_unsigned_long pid) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXApplication_ProcessID(swigCPtr, SWIGTYPE_p_unsigned_long.getCPtr(pid));
    return ret;
  }

  public virtual ADLX_RESULT Name(SWIGTYPE_p_p_wchar_t ppAppName) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXApplication_Name(swigCPtr, SWIGTYPE_p_p_wchar_t.getCPtr(ppAppName));
    return ret;
  }

  public virtual ADLX_RESULT FullPath(SWIGTYPE_p_p_wchar_t ppAppPath) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXApplication_FullPath(swigCPtr, SWIGTYPE_p_p_wchar_t.getCPtr(ppAppPath));
    return ret;
  }

  public virtual ADLX_RESULT GPUDependencyType(SWIGTYPE_p_ADLX_APP_GPU_DEPENDENCY gpuDependency) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXApplication_GPUDependencyType(swigCPtr, SWIGTYPE_p_ADLX_APP_GPU_DEPENDENCY.getCPtr(gpuDependency));
    return ret;
  }

}
