//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXDisplayConnectivityExperience : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXDisplayConnectivityExperience(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXDisplayConnectivityExperience_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXDisplayConnectivityExperience obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXDisplayConnectivityExperience obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXDisplayConnectivityExperience(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXDisplayConnectivityExperience_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedHDMIQualityDetection(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_IsSupportedHDMIQualityDetection(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT IsSupportedDPLink(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_IsSupportedDPLink(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT IsEnabledHDMIQualityDetection(SWIGTYPE_p_bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_IsEnabledHDMIQualityDetection(swigCPtr, SWIGTYPE_p_bool.getCPtr(enabled));
    return ret;
  }

  public virtual ADLX_RESULT SetEnabledHDMIQualityDetection(bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_SetEnabledHDMIQualityDetection(swigCPtr, enabled);
    return ret;
  }

  public virtual ADLX_RESULT GetDPLinkRate(SWIGTYPE_p_ADLX_DP_LINK_RATE linkRate) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_GetDPLinkRate(swigCPtr, SWIGTYPE_p_ADLX_DP_LINK_RATE.getCPtr(linkRate));
    return ret;
  }

  public virtual ADLX_RESULT GetNumberOfActiveLanes(SWIGTYPE_p_unsigned_int numActiveLanes) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_GetNumberOfActiveLanes(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(numActiveLanes));
    return ret;
  }

  public virtual ADLX_RESULT GetNumberOfTotalLanes(SWIGTYPE_p_unsigned_int numTotalLanes) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_GetNumberOfTotalLanes(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(numTotalLanes));
    return ret;
  }

  public virtual ADLX_RESULT GetRelativePreEmphasis(SWIGTYPE_p_int relativePreEmphasis) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_GetRelativePreEmphasis(swigCPtr, SWIGTYPE_p_int.getCPtr(relativePreEmphasis));
    return ret;
  }

  public virtual ADLX_RESULT SetRelativePreEmphasis(int relativePreEmphasis) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_SetRelativePreEmphasis(swigCPtr, relativePreEmphasis);
    return ret;
  }

  public virtual ADLX_RESULT GetRelativeVoltageSwing(SWIGTYPE_p_int relativeVoltageSwing) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_GetRelativeVoltageSwing(swigCPtr, SWIGTYPE_p_int.getCPtr(relativeVoltageSwing));
    return ret;
  }

  public virtual ADLX_RESULT SetRelativeVoltageSwing(int relativeVoltageSwing) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_SetRelativeVoltageSwing(swigCPtr, relativeVoltageSwing);
    return ret;
  }

  public virtual ADLX_RESULT IsEnabledLinkProtection(SWIGTYPE_p_bool enabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXDisplayConnectivityExperience_IsEnabledLinkProtection(swigCPtr, SWIGTYPE_p_bool.getCPtr(enabled));
    return ret;
  }

}
