//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXSmartShiftMax : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXSmartShiftMax(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXSmartShiftMax_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXSmartShiftMax obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXSmartShiftMax obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXSmartShiftMax(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXSmartShiftMax_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsSupported(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSmartShiftMax_IsSupported(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT GetBiasMode(SWIGTYPE_p_ADLX_SSM_BIAS_MODE mode) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSmartShiftMax_GetBiasMode(swigCPtr, SWIGTYPE_p_ADLX_SSM_BIAS_MODE.getCPtr(mode));
    return ret;
  }

  public virtual ADLX_RESULT SetBiasMode(ADLX_SSM_BIAS_MODE mode) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSmartShiftMax_SetBiasMode(swigCPtr, (int)mode);
    return ret;
  }

  public virtual ADLX_RESULT GetBiasRange(ADLX_IntRange range) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSmartShiftMax_GetBiasRange(swigCPtr, ADLX_IntRange.getCPtr(range));
    return ret;
  }

  public virtual ADLX_RESULT GetBias(SWIGTYPE_p_int bias) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSmartShiftMax_GetBias(swigCPtr, SWIGTYPE_p_int.getCPtr(bias));
    return ret;
  }

  public virtual ADLX_RESULT SetBias(int bias) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXSmartShiftMax_SetBias(swigCPtr, bias);
    return ret;
  }

}
