//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IADLXVideoUpscale : IADLXInterface {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal IADLXVideoUpscale(global::System.IntPtr cPtr, bool cMemoryOwn) : base(ADLXPINVOKE.IADLXVideoUpscale_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IADLXVideoUpscale obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(IADLXVideoUpscale obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          ADLXPINVOKE.delete_IADLXVideoUpscale(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public new static SWIGTYPE_p_wchar_t IID() {
    global::System.IntPtr cPtr = ADLXPINVOKE.IADLXVideoUpscale_IID();
    SWIGTYPE_p_wchar_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_wchar_t(cPtr, false);
    return ret;
  }

  public virtual ADLX_RESULT IsSupported(SWIGTYPE_p_bool supported) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVideoUpscale_IsSupported(swigCPtr, SWIGTYPE_p_bool.getCPtr(supported));
    return ret;
  }

  public virtual ADLX_RESULT IsEnabled(SWIGTYPE_p_bool isEnabled) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVideoUpscale_IsEnabled(swigCPtr, SWIGTYPE_p_bool.getCPtr(isEnabled));
    return ret;
  }

  public virtual ADLX_RESULT GetSharpnessRange(ADLX_IntRange range) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVideoUpscale_GetSharpnessRange(swigCPtr, ADLX_IntRange.getCPtr(range));
    return ret;
  }

  public virtual ADLX_RESULT GetSharpness(SWIGTYPE_p_int currentMinRes) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVideoUpscale_GetSharpness(swigCPtr, SWIGTYPE_p_int.getCPtr(currentMinRes));
    return ret;
  }

  public virtual ADLX_RESULT SetEnabled(bool enable) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVideoUpscale_SetEnabled(swigCPtr, enable);
    return ret;
  }

  public virtual ADLX_RESULT SetSharpness(int minSharp) {
    ADLX_RESULT ret = (ADLX_RESULT)ADLXPINVOKE.IADLXVideoUpscale_SetSharpness(swigCPtr, minSharp);
    return ret;
  }

}
