//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_pixtx_gamma_encoding_type_t {
  CTL_PIXTX_GAMMA_ENCODING_TYPE_SRGB = 0,
  CTL_PIXTX_GAMMA_ENCODING_TYPE_REC709 = 1,
  CTL_PIXTX_GAMMA_ENCODING_TYPE_ST2084 = 2,
  CTL_PIXTX_GAMMA_ENCODING_TYPE_HLG = 3,
  CTL_PIXTX_GAMMA_ENCODING_TYPE_LINEAR = 4,
  CTL_PIXTX_GAMMA_ENCODING_TYPE_MAX
}

}
