//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_init_flag_t : uint {
  CTL_INIT_FLAG_USE_LEVEL_ZERO = (1 << 0),
  CTL_INIT_FLAG_MAX = 2147483648
}

}
