//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_pixtx_color_primaries_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_pixtx_color_primaries_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_pixtx_color_primaries_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_pixtx_color_primaries_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_pixtx_color_primaries_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_pixtx_color_primaries_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      IGCLPINVOKE.ctl_pixtx_color_primaries_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_pixtx_color_primaries_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      IGCLPINVOKE.ctl_pixtx_color_primaries_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = IGCLPINVOKE.ctl_pixtx_color_primaries_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public double xR {
    set {
      IGCLPINVOKE.ctl_pixtx_color_primaries_t_xR_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_pixtx_color_primaries_t_xR_get(swigCPtr);
      return ret;
    } 
  }

  public double yR {
    set {
      IGCLPINVOKE.ctl_pixtx_color_primaries_t_yR_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_pixtx_color_primaries_t_yR_get(swigCPtr);
      return ret;
    } 
  }

  public double xG {
    set {
      IGCLPINVOKE.ctl_pixtx_color_primaries_t_xG_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_pixtx_color_primaries_t_xG_get(swigCPtr);
      return ret;
    } 
  }

  public double yG {
    set {
      IGCLPINVOKE.ctl_pixtx_color_primaries_t_yG_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_pixtx_color_primaries_t_yG_get(swigCPtr);
      return ret;
    } 
  }

  public double xB {
    set {
      IGCLPINVOKE.ctl_pixtx_color_primaries_t_xB_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_pixtx_color_primaries_t_xB_get(swigCPtr);
      return ret;
    } 
  }

  public double yB {
    set {
      IGCLPINVOKE.ctl_pixtx_color_primaries_t_yB_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_pixtx_color_primaries_t_yB_get(swigCPtr);
      return ret;
    } 
  }

  public double xW {
    set {
      IGCLPINVOKE.ctl_pixtx_color_primaries_t_xW_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_pixtx_color_primaries_t_xW_get(swigCPtr);
      return ret;
    } 
  }

  public double yW {
    set {
      IGCLPINVOKE.ctl_pixtx_color_primaries_t_yW_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_pixtx_color_primaries_t_yW_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_pixtx_color_primaries_t() : this(IGCLPINVOKE.new_ctl_pixtx_color_primaries_t(), true) {
  }

}

}
