//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_wire_format_color_model_t {
  CTL_WIRE_FORMAT_COLOR_MODEL_RGB = 0,
  CTL_WIRE_FORMAT_COLOR_MODEL_YCBCR_420 = 1,
  CTL_WIRE_FORMAT_COLOR_MODEL_YCBCR_422 = 2,
  CTL_WIRE_FORMAT_COLOR_MODEL_YCBCR_444 = 3,
  CTL_WIRE_FORMAT_COLOR_MODEL_MAX
}

}
