//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_wire_format_operation_type_t {
  CTL_WIRE_FORMAT_OPERATION_TYPE_GET = 0,
  CTL_WIRE_FORMAT_OPERATION_TYPE_SET = 1,
  CTL_WIRE_FORMAT_OPERATION_TYPE_RESTORE_DEFAULT = 2,
  CTL_WIRE_FORMAT_OPERATION_TYPE_MAX
}

}
