//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_power_optimization_lrr_flag_t : uint {
  CTL_POWER_OPTIMIZATION_LRR_FLAG_LRR10 = (1 << 0),
  CTL_POWER_OPTIMIZATION_LRR_FLAG_LRR20 = (1 << 1),
  CTL_POWER_OPTIMIZATION_LRR_FLAG_LRR25 = (1 << 2),
  CTL_POWER_OPTIMIZATION_LRR_FLAG_ALRR = (1 << 3),
  CTL_POWER_OPTIMIZATION_LRR_FLAG_UBLRR = (1 << 4),
  CTL_POWER_OPTIMIZATION_LRR_FLAG_UBZRR = (1 << 5),
  CTL_POWER_OPTIMIZATION_LRR_FLAG_MAX = 2147483648
}

}
