//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_pixtx_color_space_t {
  CTL_PIXTX_COLOR_SPACE_REC709 = 0,
  CTL_PIXTX_COLOR_SPACE_REC2020 = 1,
  CTL_PIXTX_COLOR_SPACE_ADOBE_RGB = 2,
  CTL_PIXTX_COLOR_SPACE_P3_D65 = 3,
  CTL_PIXTX_COLOR_SPACE_P3_DCI = 4,
  CTL_PIXTX_COLOR_SPACE_P3_D60 = 5,
  CTL_PIXTX_COLOR_SPACE_CUSTOM = 65535,
  CTL_PIXTX_COLOR_SPACE_MAX
}

}
