//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_freq_throttle_reason_flag_t : uint {
  CTL_FREQ_THROTTLE_REASON_FLAG_AVE_PWR_CAP = (1 << 0),
  CTL_FREQ_THROTTLE_REASON_FLAG_BURST_PWR_CAP = (1 << 1),
  CTL_FREQ_THROTTLE_REASON_FLAG_CURRENT_LIMIT = (1 << 2),
  CTL_FREQ_THROTTLE_REASON_FLAG_THERMAL_LIMIT = (1 << 3),
  CTL_FREQ_THROTTLE_REASON_FLAG_PSU_ALERT = (1 << 4),
  CTL_FREQ_THROTTLE_REASON_FLAG_SW_RANGE = (1 << 5),
  CTL_FREQ_THROTTLE_REASON_FLAG_HW_RANGE = (1 << 6),
  CTL_FREQ_THROTTLE_REASON_FLAG_MAX = 2147483648
}

}
