//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_display_properties_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_display_properties_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_display_properties_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_display_properties_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_display_properties_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_display_properties_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      IGCLPINVOKE.ctl_display_properties_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_properties_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      IGCLPINVOKE.ctl_display_properties_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = IGCLPINVOKE.ctl_display_properties_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_os_display_encoder_identifier_t Os_display_encoder_handle {
    set {
      IGCLPINVOKE.ctl_display_properties_t_Os_display_encoder_handle_set(swigCPtr, ctl_os_display_encoder_identifier_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_display_properties_t_Os_display_encoder_handle_get(swigCPtr);
      ctl_os_display_encoder_identifier_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_os_display_encoder_identifier_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_display_output_types_t Type {
    set {
      IGCLPINVOKE.ctl_display_properties_t_Type_set(swigCPtr, (int)value);
    } 
    get {
      ctl_display_output_types_t ret = (ctl_display_output_types_t)IGCLPINVOKE.ctl_display_properties_t_Type_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_attached_display_mux_type_t AttachedDisplayMuxType {
    set {
      IGCLPINVOKE.ctl_display_properties_t_AttachedDisplayMuxType_set(swigCPtr, (int)value);
    } 
    get {
      ctl_attached_display_mux_type_t ret = (ctl_attached_display_mux_type_t)IGCLPINVOKE.ctl_display_properties_t_AttachedDisplayMuxType_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_display_output_types_t ProtocolConverterOutput {
    set {
      IGCLPINVOKE.ctl_display_properties_t_ProtocolConverterOutput_set(swigCPtr, (int)value);
    } 
    get {
      ctl_display_output_types_t ret = (ctl_display_output_types_t)IGCLPINVOKE.ctl_display_properties_t_ProtocolConverterOutput_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_revision_datatype_t SupportedSpec {
    set {
      IGCLPINVOKE.ctl_display_properties_t_SupportedSpec_set(swigCPtr, ctl_revision_datatype_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_display_properties_t_SupportedSpec_get(swigCPtr);
      ctl_revision_datatype_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_revision_datatype_t(cPtr, false);
      return ret;
    } 
  }

  public uint SupportedOutputBPCFlags {
    set {
      IGCLPINVOKE.ctl_display_properties_t_SupportedOutputBPCFlags_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_properties_t_SupportedOutputBPCFlags_get(swigCPtr);
      return ret;
    } 
  }

  public uint ProtocolConverterType {
    set {
      IGCLPINVOKE.ctl_display_properties_t_ProtocolConverterType_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_properties_t_ProtocolConverterType_get(swigCPtr);
      return ret;
    } 
  }

  public uint DisplayConfigFlags {
    set {
      IGCLPINVOKE.ctl_display_properties_t_DisplayConfigFlags_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_properties_t_DisplayConfigFlags_get(swigCPtr);
      return ret;
    } 
  }

  public uint FeatureEnabledFlags {
    set {
      IGCLPINVOKE.ctl_display_properties_t_FeatureEnabledFlags_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_properties_t_FeatureEnabledFlags_get(swigCPtr);
      return ret;
    } 
  }

  public uint FeatureSupportedFlags {
    set {
      IGCLPINVOKE.ctl_display_properties_t_FeatureSupportedFlags_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_properties_t_FeatureSupportedFlags_get(swigCPtr);
      return ret;
    } 
  }

  public uint AdvancedFeatureEnabledFlags {
    set {
      IGCLPINVOKE.ctl_display_properties_t_AdvancedFeatureEnabledFlags_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_properties_t_AdvancedFeatureEnabledFlags_get(swigCPtr);
      return ret;
    } 
  }

  public uint AdvancedFeatureSupportedFlags {
    set {
      IGCLPINVOKE.ctl_display_properties_t_AdvancedFeatureSupportedFlags_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_properties_t_AdvancedFeatureSupportedFlags_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_display_timing_t Display_Timing_Info {
    set {
      IGCLPINVOKE.ctl_display_properties_t_Display_Timing_Info_set(swigCPtr, ctl_display_timing_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_display_properties_t_Display_Timing_Info_get(swigCPtr);
      ctl_display_timing_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_display_timing_t(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int ReservedFields {
    set {
      IGCLPINVOKE.ctl_display_properties_t_ReservedFields_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_display_properties_t_ReservedFields_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public ctl_display_properties_t() : this(IGCLPINVOKE.new_ctl_display_properties_t(), true) {
  }

}

}
