//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_freq_domain_t {
  CTL_FREQ_DOMAIN_GPU = 0,
  CTL_FREQ_DOMAIN_MEMORY = 1,
  CTL_FREQ_DOMAIN_MEDIA = 2,
  CTL_FREQ_DOMAIN_MAX
}

}
