//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_3d_msaa_types_t {
  CTL_3D_MSAA_TYPES_APP_CHOICE = 0,
  CTL_3D_MSAA_TYPES_DISABLED = 1,
  CTL_3D_MSAA_TYPES_2X = 2,
  CTL_3D_MSAA_TYPES_4X = 4,
  CTL_3D_MSAA_TYPES_8X = 8,
  CTL_3D_MSAA_TYPES_16X = 16,
  CTL_3D_MSAA_TYPES_MAX
}

}
