//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_adapter_properties_flag_t : uint {
  CTL_ADAPTER_PROPERTIES_FLAG_INTEGRATED = (1 << 0),
  CTL_ADAPTER_PROPERTIES_FLAG_LDA_PRIMARY = (1 << 1),
  CTL_ADAPTER_PROPERTIES_FLAG_LDA_SECONDARY = (1 << 2),
  CTL_ADAPTER_PROPERTIES_FLAG_MAX = 2147483648
}

}
