//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_intel_display_feature_flag_t : uint {
  CTL_INTEL_DISPLAY_FEATURE_FLAG_DPST = (1 << 0),
  CTL_INTEL_DISPLAY_FEATURE_FLAG_LACE = (1 << 1),
  CTL_INTEL_DISPLAY_FEATURE_FLAG_DRRS = (1 << 2),
  CTL_INTEL_DISPLAY_FEATURE_FLAG_ARC_ADAPTIVE_SYNC_CERTIFIED = (1 << 3),
  CTL_INTEL_DISPLAY_FEATURE_FLAG_MAX = 2147483648
}

}
