//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_display_setting_quantization_range_t {
  CTL_DISPLAY_SETTING_QUANTIZATION_RANGE_DEFAULT = 0,
  CTL_DISPLAY_SETTING_QUANTIZATION_RANGE_LIMITED_RANGE = 1,
  CTL_DISPLAY_SETTING_QUANTIZATION_RANGE_FULL_RANGE = 2,
  CTL_DISPLAY_SETTING_QUANTIZATION_RANGE_MAX
}

}
