//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_3d_feature_t {
  CTL_3D_FEATURE_FRAME_PACING = 0,
  CTL_3D_FEATURE_ENDURANCE_GAMING = 1,
  CTL_3D_FEATURE_FRAME_LIMIT = 2,
  CTL_3D_FEATURE_ANISOTROPIC = 3,
  CTL_3D_FEATURE_CMAA = 4,
  CTL_3D_FEATURE_TEXTURE_FILTERING_QUALITY = 5,
  CTL_3D_FEATURE_ADAPTIVE_TESSELLATION = 6,
  CTL_3D_FEATURE_SHARPENING_FILTER = 7,
  CTL_3D_FEATURE_MSAA = 8,
  CTL_3D_FEATURE_GAMING_FLIP_MODES = 9,
  CTL_3D_FEATURE_ADAPTIVE_SYNC_PLUS = 10,
  CTL_3D_FEATURE_APP_PROFILES = 11,
  CTL_3D_FEATURE_APP_PROFILE_DETAILS = 12,
  CTL_3D_FEATURE_EMULATED_TYPED_64BIT_ATOMICS = 13,
  CTL_3D_FEATURE_VRR_WINDOWED_BLT = 14,
  CTL_3D_FEATURE_GLOBAL_OR_PER_APP = 15,
  CTL_3D_FEATURE_LOW_LATENCY = 16,
  CTL_3D_FEATURE_FRAME_GENERATION = 17,
  CTL_3D_FEATURE_MAX
}

}
