//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_pixtx_lut_sampling_type_t {
  CTL_PIXTX_LUT_SAMPLING_TYPE_UNIFORM = 0,
  CTL_PIXTX_LUT_SAMPLING_TYPE_NONUNIFORM = 1,
  CTL_PIXTX_LUT_SAMPLING_TYPE_MAX
}

}
