//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_display_orientation_t {
  CTL_DISPLAY_ORIENTATION_0 = 0,
  CTL_DISPLAY_ORIENTATION_90 = 1,
  CTL_DISPLAY_ORIENTATION_180 = 2,
  CTL_DISPLAY_ORIENTATION_270 = 3,
  CTL_DISPLAY_ORIENTATION_MAX
}

}
