//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_pixtx_pixel_format_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_pixtx_pixel_format_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_pixtx_pixel_format_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_pixtx_pixel_format_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_pixtx_pixel_format_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_pixtx_pixel_format_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      IGCLPINVOKE.ctl_pixtx_pixel_format_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_pixtx_pixel_format_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      IGCLPINVOKE.ctl_pixtx_pixel_format_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = IGCLPINVOKE.ctl_pixtx_pixel_format_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public uint BitsPerColor {
    set {
      IGCLPINVOKE.ctl_pixtx_pixel_format_t_BitsPerColor_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_pixtx_pixel_format_t_BitsPerColor_get(swigCPtr);
      return ret;
    } 
  }

  public bool IsFloat {
    set {
      IGCLPINVOKE.ctl_pixtx_pixel_format_t_IsFloat_set(swigCPtr, value);
    } 
    get {
      bool ret = IGCLPINVOKE.ctl_pixtx_pixel_format_t_IsFloat_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_pixtx_gamma_encoding_type_t EncodingType {
    set {
      IGCLPINVOKE.ctl_pixtx_pixel_format_t_EncodingType_set(swigCPtr, (int)value);
    } 
    get {
      ctl_pixtx_gamma_encoding_type_t ret = (ctl_pixtx_gamma_encoding_type_t)IGCLPINVOKE.ctl_pixtx_pixel_format_t_EncodingType_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_pixtx_color_space_t ColorSpace {
    set {
      IGCLPINVOKE.ctl_pixtx_pixel_format_t_ColorSpace_set(swigCPtr, (int)value);
    } 
    get {
      ctl_pixtx_color_space_t ret = (ctl_pixtx_color_space_t)IGCLPINVOKE.ctl_pixtx_pixel_format_t_ColorSpace_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_pixtx_color_model_t ColorModel {
    set {
      IGCLPINVOKE.ctl_pixtx_pixel_format_t_ColorModel_set(swigCPtr, (int)value);
    } 
    get {
      ctl_pixtx_color_model_t ret = (ctl_pixtx_color_model_t)IGCLPINVOKE.ctl_pixtx_pixel_format_t_ColorModel_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_pixtx_color_primaries_t ColorPrimaries {
    set {
      IGCLPINVOKE.ctl_pixtx_pixel_format_t_ColorPrimaries_set(swigCPtr, ctl_pixtx_color_primaries_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_pixtx_pixel_format_t_ColorPrimaries_get(swigCPtr);
      ctl_pixtx_color_primaries_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_pixtx_color_primaries_t(cPtr, false);
      return ret;
    } 
  }

  public double MaxBrightness {
    set {
      IGCLPINVOKE.ctl_pixtx_pixel_format_t_MaxBrightness_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_pixtx_pixel_format_t_MaxBrightness_get(swigCPtr);
      return ret;
    } 
  }

  public double MinBrightness {
    set {
      IGCLPINVOKE.ctl_pixtx_pixel_format_t_MinBrightness_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_pixtx_pixel_format_t_MinBrightness_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_pixtx_pixel_format_t() : this(IGCLPINVOKE.new_ctl_pixtx_pixel_format_t(), true) {
  }

}

}
