//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_protocol_converter_location_flag_t : uint {
  CTL_PROTOCOL_CONVERTER_LOCATION_FLAG_ONBOARD = (1 << 0),
  CTL_PROTOCOL_CONVERTER_LOCATION_FLAG_EXTERNAL = (1 << 1),
  CTL_PROTOCOL_CONVERTER_LOCATION_FLAG_MAX = 2147483648
}

}
