//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_units_t {
  CTL_UNITS_FREQUENCY_MHZ = 0,
  CTL_UNITS_OPERATIONS_GTS = 1,
  CTL_UNITS_OPERATIONS_MTS = 2,
  CTL_UNITS_VOLTAGE_VOLTS = 3,
  CTL_UNITS_POWER_WATTS = 4,
  CTL_UNITS_TEMPERATURE_CELSIUS = 5,
  CTL_UNITS_ENERGY_JOULES = 6,
  CTL_UNITS_TIME_SECONDS = 7,
  CTL_UNITS_MEMORY_BYTES = 8,
  CTL_UNITS_ANGULAR_SPEED_RPM = 9,
  CTL_UNITS_POWER_MILLIWATTS = 10,
  CTL_UNITS_PERCENT = 11,
  CTL_UNITS_MEM_SPEED_GBPS = 12,
  CTL_UNITS_VOLTAGE_MILLIVOLTS = 13,
  CTL_UNITS_BANDWIDTH_MBPS = 14,
  CTL_UNITS_UNKNOWN = 1208025087,
  CTL_UNITS_MAX
}

}
