//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_child_display_target_mode_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_child_display_target_mode_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_child_display_target_mode_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_child_display_target_mode_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_child_display_target_mode_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_child_display_target_mode_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Width {
    set {
      IGCLPINVOKE.ctl_child_display_target_mode_t_Width_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_child_display_target_mode_t_Width_get(swigCPtr);
      return ret;
    } 
  }

  public uint Height {
    set {
      IGCLPINVOKE.ctl_child_display_target_mode_t_Height_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_child_display_target_mode_t_Height_get(swigCPtr);
      return ret;
    } 
  }

  public float RefreshRate {
    set {
      IGCLPINVOKE.ctl_child_display_target_mode_t_RefreshRate_set(swigCPtr, value);
    } 
    get {
      float ret = IGCLPINVOKE.ctl_child_display_target_mode_t_RefreshRate_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int ReservedFields {
    set {
      IGCLPINVOKE.ctl_child_display_target_mode_t_ReservedFields_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_child_display_target_mode_t_ReservedFields_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public ctl_child_display_target_mode_t() : this(IGCLPINVOKE.new_ctl_child_display_target_mode_t(), true) {
  }

}

}
