//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_display_config_flag_t : uint {
  CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ACTIVE = (1 << 0),
  CTL_DISPLAY_CONFIG_FLAG_DISPLAY_ATTACHED = (1 << 1),
  CTL_DISPLAY_CONFIG_FLAG_IS_DONGLE_CONNECTED_TO_ENCODER = (1 << 2),
  CTL_DISPLAY_CONFIG_FLAG_DITHERING_ENABLED = (1 << 3),
  CTL_DISPLAY_CONFIG_FLAG_MAX = 2147483648
}

}
