//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_scaling_settings_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_scaling_settings_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_scaling_settings_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_scaling_settings_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_scaling_settings_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_scaling_settings_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      IGCLPINVOKE.ctl_scaling_settings_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_scaling_settings_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      IGCLPINVOKE.ctl_scaling_settings_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = IGCLPINVOKE.ctl_scaling_settings_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public bool Enable {
    set {
      IGCLPINVOKE.ctl_scaling_settings_t_Enable_set(swigCPtr, value);
    } 
    get {
      bool ret = IGCLPINVOKE.ctl_scaling_settings_t_Enable_get(swigCPtr);
      return ret;
    } 
  }

  public uint ScalingType {
    set {
      IGCLPINVOKE.ctl_scaling_settings_t_ScalingType_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_scaling_settings_t_ScalingType_get(swigCPtr);
      return ret;
    } 
  }

  public uint CustomScalingX {
    set {
      IGCLPINVOKE.ctl_scaling_settings_t_CustomScalingX_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_scaling_settings_t_CustomScalingX_get(swigCPtr);
      return ret;
    } 
  }

  public uint CustomScalingY {
    set {
      IGCLPINVOKE.ctl_scaling_settings_t_CustomScalingY_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_scaling_settings_t_CustomScalingY_get(swigCPtr);
      return ret;
    } 
  }

  public bool HardwareModeSet {
    set {
      IGCLPINVOKE.ctl_scaling_settings_t_HardwareModeSet_set(swigCPtr, value);
    } 
    get {
      bool ret = IGCLPINVOKE.ctl_scaling_settings_t_HardwareModeSet_get(swigCPtr);
      return ret;
    } 
  }

  public uint PreferredScalingType {
    set {
      IGCLPINVOKE.ctl_scaling_settings_t_PreferredScalingType_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_scaling_settings_t_PreferredScalingType_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_scaling_settings_t() : this(IGCLPINVOKE.new_ctl_scaling_settings_t(), true) {
  }

}

}
