//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_adaptivesync_getset_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_adaptivesync_getset_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_adaptivesync_getset_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_adaptivesync_getset_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_adaptivesync_getset_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_adaptivesync_getset_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public bool AdaptiveSync {
    set {
      IGCLPINVOKE.ctl_adaptivesync_getset_t_AdaptiveSync_set(swigCPtr, value);
    } 
    get {
      bool ret = IGCLPINVOKE.ctl_adaptivesync_getset_t_AdaptiveSync_get(swigCPtr);
      return ret;
    } 
  }

  public bool AdaptiveBalance {
    set {
      IGCLPINVOKE.ctl_adaptivesync_getset_t_AdaptiveBalance_set(swigCPtr, value);
    } 
    get {
      bool ret = IGCLPINVOKE.ctl_adaptivesync_getset_t_AdaptiveBalance_get(swigCPtr);
      return ret;
    } 
  }

  public bool AllowAsyncForHighFPS {
    set {
      IGCLPINVOKE.ctl_adaptivesync_getset_t_AllowAsyncForHighFPS_set(swigCPtr, value);
    } 
    get {
      bool ret = IGCLPINVOKE.ctl_adaptivesync_getset_t_AllowAsyncForHighFPS_get(swigCPtr);
      return ret;
    } 
  }

  public float AdaptiveBalanceStrength {
    set {
      IGCLPINVOKE.ctl_adaptivesync_getset_t_AdaptiveBalanceStrength_set(swigCPtr, value);
    } 
    get {
      float ret = IGCLPINVOKE.ctl_adaptivesync_getset_t_AdaptiveBalanceStrength_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_adaptivesync_getset_t() : this(IGCLPINVOKE.new_ctl_adaptivesync_getset_t(), true) {
  }

}

}
