//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_init_args_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_init_args_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_init_args_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_init_args_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_init_args_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_init_args_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      IGCLPINVOKE.ctl_init_args_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_init_args_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      IGCLPINVOKE.ctl_init_args_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = IGCLPINVOKE.ctl_init_args_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public uint AppVersion {
    set {
      IGCLPINVOKE.ctl_init_args_t_AppVersion_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_init_args_t_AppVersion_get(swigCPtr);
      return ret;
    } 
  }

  public uint flags {
    set {
      IGCLPINVOKE.ctl_init_args_t_flags_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_init_args_t_flags_get(swigCPtr);
      return ret;
    } 
  }

  public uint SupportedVersion {
    set {
      IGCLPINVOKE.ctl_init_args_t_SupportedVersion_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_init_args_t_SupportedVersion_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_application_id_t ApplicationUID {
    set {
      IGCLPINVOKE.ctl_init_args_t_ApplicationUID_set(swigCPtr, ctl_application_id_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_init_args_t_ApplicationUID_get(swigCPtr);
      ctl_application_id_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_application_id_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_init_args_t() : this(IGCLPINVOKE.new_ctl_init_args_t(), true) {
  }

}

}
