//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_display_timing_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_display_timing_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_display_timing_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_display_timing_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_display_timing_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_display_timing_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      IGCLPINVOKE.ctl_display_timing_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_timing_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      IGCLPINVOKE.ctl_display_timing_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = IGCLPINVOKE.ctl_display_timing_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public ulong PixelClock {
    set {
      IGCLPINVOKE.ctl_display_timing_t_PixelClock_set(swigCPtr, value);
    } 
    get {
      ulong ret = IGCLPINVOKE.ctl_display_timing_t_PixelClock_get(swigCPtr);
      return ret;
    } 
  }

  public uint HActive {
    set {
      IGCLPINVOKE.ctl_display_timing_t_HActive_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_timing_t_HActive_get(swigCPtr);
      return ret;
    } 
  }

  public uint VActive {
    set {
      IGCLPINVOKE.ctl_display_timing_t_VActive_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_timing_t_VActive_get(swigCPtr);
      return ret;
    } 
  }

  public uint HTotal {
    set {
      IGCLPINVOKE.ctl_display_timing_t_HTotal_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_timing_t_HTotal_get(swigCPtr);
      return ret;
    } 
  }

  public uint VTotal {
    set {
      IGCLPINVOKE.ctl_display_timing_t_VTotal_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_timing_t_VTotal_get(swigCPtr);
      return ret;
    } 
  }

  public uint HBlank {
    set {
      IGCLPINVOKE.ctl_display_timing_t_HBlank_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_timing_t_HBlank_get(swigCPtr);
      return ret;
    } 
  }

  public uint VBlank {
    set {
      IGCLPINVOKE.ctl_display_timing_t_VBlank_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_timing_t_VBlank_get(swigCPtr);
      return ret;
    } 
  }

  public uint HSync {
    set {
      IGCLPINVOKE.ctl_display_timing_t_HSync_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_timing_t_HSync_get(swigCPtr);
      return ret;
    } 
  }

  public uint VSync {
    set {
      IGCLPINVOKE.ctl_display_timing_t_VSync_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_display_timing_t_VSync_get(swigCPtr);
      return ret;
    } 
  }

  public float RefreshRate {
    set {
      IGCLPINVOKE.ctl_display_timing_t_RefreshRate_set(swigCPtr, value);
    } 
    get {
      float ret = IGCLPINVOKE.ctl_display_timing_t_RefreshRate_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_signal_standard_type_t SignalStandard {
    set {
      IGCLPINVOKE.ctl_display_timing_t_SignalStandard_set(swigCPtr, (int)value);
    } 
    get {
      ctl_signal_standard_type_t ret = (ctl_signal_standard_type_t)IGCLPINVOKE.ctl_display_timing_t_SignalStandard_get(swigCPtr);
      return ret;
    } 
  }

  public byte VicId {
    set {
      IGCLPINVOKE.ctl_display_timing_t_VicId_set(swigCPtr, value);
    } 
    get {
      byte ret = IGCLPINVOKE.ctl_display_timing_t_VicId_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_display_timing_t() : this(IGCLPINVOKE.new_ctl_display_timing_t(), true) {
  }

}

}
