//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_fan_speed_units_t {
  CTL_FAN_SPEED_UNITS_RPM = 0,
  CTL_FAN_SPEED_UNITS_PERCENT = 1,
  CTL_FAN_SPEED_UNITS_MAX
}

}
