//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_lace_config_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_lace_config_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_lace_config_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_lace_config_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_lace_config_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_lace_config_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      IGCLPINVOKE.ctl_lace_config_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_lace_config_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      IGCLPINVOKE.ctl_lace_config_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = IGCLPINVOKE.ctl_lace_config_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public bool Enabled {
    set {
      IGCLPINVOKE.ctl_lace_config_t_Enabled_set(swigCPtr, value);
    } 
    get {
      bool ret = IGCLPINVOKE.ctl_lace_config_t_Enabled_get(swigCPtr);
      return ret;
    } 
  }

  public uint OpTypeGet {
    set {
      IGCLPINVOKE.ctl_lace_config_t_OpTypeGet_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_lace_config_t_OpTypeGet_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_set_operation_t OpTypeSet {
    set {
      IGCLPINVOKE.ctl_lace_config_t_OpTypeSet_set(swigCPtr, (int)value);
    } 
    get {
      ctl_set_operation_t ret = (ctl_set_operation_t)IGCLPINVOKE.ctl_lace_config_t_OpTypeSet_get(swigCPtr);
      return ret;
    } 
  }

  public uint Trigger {
    set {
      IGCLPINVOKE.ctl_lace_config_t_Trigger_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_lace_config_t_Trigger_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_lace_aggr_config_t LaceConfig {
    set {
      IGCLPINVOKE.ctl_lace_config_t_LaceConfig_set(swigCPtr, ctl_lace_aggr_config_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_lace_config_t_LaceConfig_get(swigCPtr);
      ctl_lace_aggr_config_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_lace_aggr_config_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_lace_config_t() : this(IGCLPINVOKE.new_ctl_lace_config_t(), true) {
  }

}

}
