//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_display_setting_picture_ar_flag_t : uint {
  CTL_DISPLAY_SETTING_PICTURE_AR_FLAG_DEFAULT = (1 << 0),
  CTL_DISPLAY_SETTING_PICTURE_AR_FLAG_DISABLED = (1 << 1),
  CTL_DISPLAY_SETTING_PICTURE_AR_FLAG_AR_4_3 = (1 << 2),
  CTL_DISPLAY_SETTING_PICTURE_AR_FLAG_AR_16_9 = (1 << 3),
  CTL_DISPLAY_SETTING_PICTURE_AR_FLAG_AR_64_27 = (1 << 4),
  CTL_DISPLAY_SETTING_PICTURE_AR_FLAG_AR_256_135 = (1 << 5),
  CTL_DISPLAY_SETTING_PICTURE_AR_FLAG_MAX = 2147483648
}

}
