//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_intel_arc_sync_profile_t {
  CTL_INTEL_ARC_SYNC_PROFILE_INVALID = 0,
  CTL_INTEL_ARC_SYNC_PROFILE_RECOMMENDED = 1,
  CTL_INTEL_ARC_SYNC_PROFILE_EXCELLENT = 2,
  CTL_INTEL_ARC_SYNC_PROFILE_GOOD = 3,
  CTL_INTEL_ARC_SYNC_PROFILE_COMPATIBLE = 4,
  CTL_INTEL_ARC_SYNC_PROFILE_OFF = 5,
  CTL_INTEL_ARC_SYNC_PROFILE_VESA = 6,
  CTL_INTEL_ARC_SYNC_PROFILE_CUSTOM = 7,
  CTL_INTEL_ARC_SYNC_PROFILE_MAX
}

}
