//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_edid_management_out_flag_t : uint {
  CTL_EDID_MANAGEMENT_OUT_FLAG_OS_CONN_NOTIFICATION = (1 << 0),
  CTL_EDID_MANAGEMENT_OUT_FLAG_SUPPLIED_EDID = (1 << 1),
  CTL_EDID_MANAGEMENT_OUT_FLAG_MONITOR_EDID = (1 << 2),
  CTL_EDID_MANAGEMENT_OUT_FLAG_DISPLAY_CONNECTED = (1 << 3),
  CTL_EDID_MANAGEMENT_OUT_FLAG_MAX = 2147483648
}

}
