//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_pixtx_block_type_t {
  CTL_PIXTX_BLOCK_TYPE_1D_LUT = 1,
  CTL_PIXTX_BLOCK_TYPE_3D_LUT = 2,
  CTL_PIXTX_BLOCK_TYPE_3X3_MATRIX = 3,
  CTL_PIXTX_BLOCK_TYPE_3X3_MATRIX_AND_OFFSETS = 4,
  CTL_PIXTX_BLOCK_TYPE_MAX
}

}
