//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_psu_type_t {
  CTL_PSU_TYPE_PSU_NONE = 0,
  CTL_PSU_TYPE_PSU_PCIE = 1,
  CTL_PSU_TYPE_PSU_6PIN = 2,
  CTL_PSU_TYPE_PSU_8PIN = 3,
  CTL_PSU_TYPE_MAX
}

}
