//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_3d_cmaa_types_t {
  CTL_3D_CMAA_TYPES_TURN_OFF = 0,
  CTL_3D_CMAA_TYPES_OVERRIDE_MSAA = 1,
  CTL_3D_CMAA_TYPES_ENHANCE_APPLICATION = 2,
  CTL_3D_CMAA_TYPES_MAX
}

}
