//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_3d_tier_profile_flag_t : uint {
  CTL_3D_TIER_PROFILE_FLAG_TIER_1 = (1 << 0),
  CTL_3D_TIER_PROFILE_FLAG_TIER_2 = (1 << 1),
  CTL_3D_TIER_PROFILE_FLAG_TIER_RECOMMENDED = (1 << 30),
  CTL_3D_TIER_PROFILE_FLAG_MAX = 2147483648
}

}
