//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_display_setting_audio_t {
  CTL_DISPLAY_SETTING_AUDIO_DEFAULT = 0,
  CTL_DISPLAY_SETTING_AUDIO_DISABLED = 1,
  CTL_DISPLAY_SETTING_AUDIO_MAX
}

}
