//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_3d_global_or_per_app_types_t {
  CTL_3D_GLOBAL_OR_PER_APP_TYPES_NONE = 0,
  CTL_3D_GLOBAL_OR_PER_APP_TYPES_PER_APP = 1,
  CTL_3D_GLOBAL_OR_PER_APP_TYPES_GLOBAL = 2,
  CTL_3D_GLOBAL_OR_PER_APP_TYPES_MAX
}

}
