//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_temp_sensors_t {
  CTL_TEMP_SENSORS_GLOBAL = 0,
  CTL_TEMP_SENSORS_GPU = 1,
  CTL_TEMP_SENSORS_MEMORY = 2,
  CTL_TEMP_SENSORS_GLOBAL_MIN = 3,
  CTL_TEMP_SENSORS_GPU_MIN = 4,
  CTL_TEMP_SENSORS_MEMORY_MIN = 5,
  CTL_TEMP_SENSORS_MAX
}

}
