//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_power_source_t {
  CTL_POWER_SOURCE_AC = 0,
  CTL_POWER_SOURCE_DC = 1,
  CTL_POWER_SOURCE_MAX
}

}
