//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_pixtx_color_model_t {
  CTL_PIXTX_COLOR_MODEL_RGB_FR = 0,
  CTL_PIXTX_COLOR_MODEL_RGB_LR = 1,
  CTL_PIXTX_COLOR_MODEL_YCBCR_422_FR = 2,
  CTL_PIXTX_COLOR_MODEL_YCBCR_422_LR = 3,
  CTL_PIXTX_COLOR_MODEL_YCBCR_420_FR = 4,
  CTL_PIXTX_COLOR_MODEL_YCBCR_420_LR = 5,
  CTL_PIXTX_COLOR_MODEL_YCBCR_444_FR = 6,
  CTL_PIXTX_COLOR_MODEL_YCBCR_444_LR = 7,
  CTL_PIXTX_COLOR_MODEL_MAX
}

}
