//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_property_value_type_t {
  CTL_PROPERTY_VALUE_TYPE_BOOL = 0,
  CTL_PROPERTY_VALUE_TYPE_FLOAT = 1,
  CTL_PROPERTY_VALUE_TYPE_INT32 = 2,
  CTL_PROPERTY_VALUE_TYPE_UINT32 = 3,
  CTL_PROPERTY_VALUE_TYPE_ENUM = 4,
  CTL_PROPERTY_VALUE_TYPE_CUSTOM = 5,
  CTL_PROPERTY_VALUE_TYPE_MAX
}

}
