//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_endurance_gaming2_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_endurance_gaming2_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_endurance_gaming2_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_endurance_gaming2_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_endurance_gaming2_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_endurance_gaming2_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public ctl_3d_endurance_gaming_control_t EGControl {
    set {
      IGCLPINVOKE.ctl_endurance_gaming2_t_EGControl_set(swigCPtr, (int)value);
    } 
    get {
      ctl_3d_endurance_gaming_control_t ret = (ctl_3d_endurance_gaming_control_t)IGCLPINVOKE.ctl_endurance_gaming2_t_EGControl_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_3d_endurance_gaming_mode_t EGMode {
    set {
      IGCLPINVOKE.ctl_endurance_gaming2_t_EGMode_set(swigCPtr, (int)value);
    } 
    get {
      ctl_3d_endurance_gaming_mode_t ret = (ctl_3d_endurance_gaming_mode_t)IGCLPINVOKE.ctl_endurance_gaming2_t_EGMode_get(swigCPtr);
      return ret;
    } 
  }

  public bool IsFPRequired {
    set {
      IGCLPINVOKE.ctl_endurance_gaming2_t_IsFPRequired_set(swigCPtr, value);
    } 
    get {
      bool ret = IGCLPINVOKE.ctl_endurance_gaming2_t_IsFPRequired_get(swigCPtr);
      return ret;
    } 
  }

  public double TargetFPS {
    set {
      IGCLPINVOKE.ctl_endurance_gaming2_t_TargetFPS_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_endurance_gaming2_t_TargetFPS_get(swigCPtr);
      return ret;
    } 
  }

  public double RefreshRate {
    set {
      IGCLPINVOKE.ctl_endurance_gaming2_t_RefreshRate_set(swigCPtr, value);
    } 
    get {
      double ret = IGCLPINVOKE.ctl_endurance_gaming2_t_RefreshRate_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int Reserved {
    set {
      IGCLPINVOKE.ctl_endurance_gaming2_t_Reserved_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_endurance_gaming2_t_Reserved_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public ctl_endurance_gaming2_t() : this(IGCLPINVOKE.new_ctl_endurance_gaming2_t(), true) {
  }

}

}
