//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_encoder_config_flag_t : uint {
  CTL_ENCODER_CONFIG_FLAG_INTERNAL_DISPLAY = (1 << 0),
  CTL_ENCODER_CONFIG_FLAG_VESA_TILED_DISPLAY = (1 << 1),
  CTL_ENCODER_CONFIG_FLAG_TYPEC_CAPABLE = (1 << 2),
  CTL_ENCODER_CONFIG_FLAG_TBT_CAPABLE = (1 << 3),
  CTL_ENCODER_CONFIG_FLAG_DITHERING_SUPPORTED = (1 << 4),
  CTL_ENCODER_CONFIG_FLAG_VIRTUAL_DISPLAY = (1 << 5),
  CTL_ENCODER_CONFIG_FLAG_HIDDEN_DISPLAY = (1 << 6),
  CTL_ENCODER_CONFIG_FLAG_COLLAGE_DISPLAY = (1 << 7),
  CTL_ENCODER_CONFIG_FLAG_SPLIT_DISPLAY = (1 << 8),
  CTL_ENCODER_CONFIG_FLAG_COMPANION_DISPLAY = (1 << 9),
  CTL_ENCODER_CONFIG_FLAG_MGPU_COLLAGE_DISPLAY = (1 << 10),
  CTL_ENCODER_CONFIG_FLAG_MAX = 2147483648
}

}
