//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_genlock_operation_t {
  CTL_GENLOCK_OPERATION_GET_TIMING_DETAILS = 0,
  CTL_GENLOCK_OPERATION_VALIDATE = 1,
  CTL_GENLOCK_OPERATION_ENABLE = 2,
  CTL_GENLOCK_OPERATION_DISABLE = 3,
  CTL_GENLOCK_OPERATION_GET_TOPOLOGY = 4,
  CTL_GENLOCK_OPERATION_MAX
}

}
