//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_set_operation_t {
  CTL_SET_OPERATION_RESTORE_DEFAULT = 0,
  CTL_SET_OPERATION_CUSTOM = 1,
  CTL_SET_OPERATION_MAX
}

}
