//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_rect_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_rect_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_rect_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_rect_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_rect_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_rect_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int Left {
    set {
      IGCLPINVOKE.ctl_rect_t_Left_set(swigCPtr, value);
    } 
    get {
      int ret = IGCLPINVOKE.ctl_rect_t_Left_get(swigCPtr);
      return ret;
    } 
  }

  public int Top {
    set {
      IGCLPINVOKE.ctl_rect_t_Top_set(swigCPtr, value);
    } 
    get {
      int ret = IGCLPINVOKE.ctl_rect_t_Top_get(swigCPtr);
      return ret;
    } 
  }

  public int Right {
    set {
      IGCLPINVOKE.ctl_rect_t_Right_set(swigCPtr, value);
    } 
    get {
      int ret = IGCLPINVOKE.ctl_rect_t_Right_get(swigCPtr);
      return ret;
    } 
  }

  public int Bottom {
    set {
      IGCLPINVOKE.ctl_rect_t_Bottom_set(swigCPtr, value);
    } 
    get {
      int ret = IGCLPINVOKE.ctl_rect_t_Bottom_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_rect_t() : this(IGCLPINVOKE.new_ctl_rect_t(), true) {
  }

}

}
