//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_supported_functions_flag_t : uint {
  CTL_SUPPORTED_FUNCTIONS_FLAG_DISPLAY = (1 << 0),
  CTL_SUPPORTED_FUNCTIONS_FLAG_3D = (1 << 1),
  CTL_SUPPORTED_FUNCTIONS_FLAG_MEDIA = (1 << 2),
  CTL_SUPPORTED_FUNCTIONS_FLAG_MAX = 2147483648
}

}
