//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_pixtx_matrix_config_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_pixtx_matrix_config_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_pixtx_matrix_config_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_pixtx_matrix_config_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_pixtx_matrix_config_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_pixtx_matrix_config_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      IGCLPINVOKE.ctl_pixtx_matrix_config_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_pixtx_matrix_config_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      IGCLPINVOKE.ctl_pixtx_matrix_config_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = IGCLPINVOKE.ctl_pixtx_matrix_config_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_double PreOffsets {
    set {
      IGCLPINVOKE.ctl_pixtx_matrix_config_t_PreOffsets_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_pixtx_matrix_config_t_PreOffsets_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_double PostOffsets {
    set {
      IGCLPINVOKE.ctl_pixtx_matrix_config_t_PostOffsets_set(swigCPtr, SWIGTYPE_p_double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_pixtx_matrix_config_t_PostOffsets_get(swigCPtr);
      SWIGTYPE_p_double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_double(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_a_3__double Matrix {
    set {
      IGCLPINVOKE.ctl_pixtx_matrix_config_t_Matrix_set(swigCPtr, SWIGTYPE_p_a_3__double.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_pixtx_matrix_config_t_Matrix_get(swigCPtr);
      SWIGTYPE_p_a_3__double ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_a_3__double(cPtr, false);
      return ret;
    } 
  }

  public ctl_pixtx_matrix_config_t() : this(IGCLPINVOKE.new_ctl_pixtx_matrix_config_t(), true) {
  }

}

}
