//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public class ctl_video_processing_feature_getset_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_video_processing_feature_getset_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_video_processing_feature_getset_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_video_processing_feature_getset_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_video_processing_feature_getset_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          IGCLPINVOKE.delete_ctl_video_processing_feature_getset_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint Size {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_Size_set(swigCPtr, value);
    } 
    get {
      uint ret = IGCLPINVOKE.ctl_video_processing_feature_getset_t_Size_get(swigCPtr);
      return ret;
    } 
  }

  public byte Version {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_Version_set(swigCPtr, value);
    } 
    get {
      byte ret = IGCLPINVOKE.ctl_video_processing_feature_getset_t_Version_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_video_processing_feature_t FeatureType {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_FeatureType_set(swigCPtr, (int)value);
    } 
    get {
      ctl_video_processing_feature_t ret = (ctl_video_processing_feature_t)IGCLPINVOKE.ctl_video_processing_feature_getset_t_FeatureType_get(swigCPtr);
      return ret;
    } 
  }

  public string ApplicationName {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_ApplicationName_set(swigCPtr, value);
    } 
    get {
      string ret = IGCLPINVOKE.ctl_video_processing_feature_getset_t_ApplicationName_get(swigCPtr);
      return ret;
    } 
  }

  public sbyte ApplicationNameLength {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_ApplicationNameLength_set(swigCPtr, value);
    } 
    get {
      sbyte ret = IGCLPINVOKE.ctl_video_processing_feature_getset_t_ApplicationNameLength_get(swigCPtr);
      return ret;
    } 
  }

  public bool bSet {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_bSet_set(swigCPtr, value);
    } 
    get {
      bool ret = IGCLPINVOKE.ctl_video_processing_feature_getset_t_bSet_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_property_value_type_t ValueType {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_ValueType_set(swigCPtr, (int)value);
    } 
    get {
      ctl_property_value_type_t ret = (ctl_property_value_type_t)IGCLPINVOKE.ctl_video_processing_feature_getset_t_ValueType_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_property_t Value {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_Value_set(swigCPtr, ctl_property_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_video_processing_feature_getset_t_Value_get(swigCPtr);
      ctl_property_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_property_t(cPtr, false);
      return ret;
    } 
  }

  public int CustomValueSize {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_CustomValueSize_set(swigCPtr, value);
    } 
    get {
      int ret = IGCLPINVOKE.ctl_video_processing_feature_getset_t_CustomValueSize_get(swigCPtr);
      return ret;
    } 
  }

  public SWIGTYPE_p_void pCustomValue {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_pCustomValue_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_video_processing_feature_getset_t_pCustomValue_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_unsigned_int ReservedFields {
    set {
      IGCLPINVOKE.ctl_video_processing_feature_getset_t_ReservedFields_set(swigCPtr, SWIGTYPE_p_unsigned_int.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = IGCLPINVOKE.ctl_video_processing_feature_getset_t_ReservedFields_get(swigCPtr);
      SWIGTYPE_p_unsigned_int ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_unsigned_int(cPtr, false);
      return ret;
    } 
  }

  public ctl_video_processing_feature_getset_t() : this(IGCLPINVOKE.new_ctl_video_processing_feature_getset_t(), true) {
  }

}

}
