//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace IGCLWrapper {

public enum ctl_power_optimization_flag_t : uint {
  CTL_POWER_OPTIMIZATION_FLAG_FBC = (1 << 0),
  CTL_POWER_OPTIMIZATION_FLAG_PSR = (1 << 1),
  CTL_POWER_OPTIMIZATION_FLAG_DPST = (1 << 2),
  CTL_POWER_OPTIMIZATION_FLAG_LRR = (1 << 3),
  CTL_POWER_OPTIMIZATION_FLAG_LACE = (1 << 4),
  CTL_POWER_OPTIMIZATION_FLAG_MAX = 2147483648
}

}
