//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlLibraryBindings {

public class ctl_combined_display_child_info_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_combined_display_child_info_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_combined_display_child_info_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_combined_display_child_info_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_combined_display_child_info_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CtlLibraryPINVOKE.delete_ctl_combined_display_child_info_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public SWIGTYPE_p__ctl_display_output_handle_t hDisplayOutput {
    set {
      CtlLibraryPINVOKE.ctl_combined_display_child_info_t_hDisplayOutput_set(swigCPtr, SWIGTYPE_p__ctl_display_output_handle_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlLibraryPINVOKE.ctl_combined_display_child_info_t_hDisplayOutput_get(swigCPtr);
      SWIGTYPE_p__ctl_display_output_handle_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p__ctl_display_output_handle_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_rect_t FbSrc {
    set {
      CtlLibraryPINVOKE.ctl_combined_display_child_info_t_FbSrc_set(swigCPtr, ctl_rect_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlLibraryPINVOKE.ctl_combined_display_child_info_t_FbSrc_get(swigCPtr);
      ctl_rect_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_rect_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_rect_t FbPos {
    set {
      CtlLibraryPINVOKE.ctl_combined_display_child_info_t_FbPos_set(swigCPtr, ctl_rect_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlLibraryPINVOKE.ctl_combined_display_child_info_t_FbPos_get(swigCPtr);
      ctl_rect_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_rect_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_display_orientation_t DisplayOrientation {
    set {
      CtlLibraryPINVOKE.ctl_combined_display_child_info_t_DisplayOrientation_set(swigCPtr, (int)value);
    } 
    get {
      ctl_display_orientation_t ret = (ctl_display_orientation_t)CtlLibraryPINVOKE.ctl_combined_display_child_info_t_DisplayOrientation_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_child_display_target_mode_t TargetMode {
    set {
      CtlLibraryPINVOKE.ctl_combined_display_child_info_t_TargetMode_set(swigCPtr, ctl_child_display_target_mode_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlLibraryPINVOKE.ctl_combined_display_child_info_t_TargetMode_get(swigCPtr);
      ctl_child_display_target_mode_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_child_display_target_mode_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_combined_display_child_info_t() : this(CtlLibraryPINVOKE.new_ctl_combined_display_child_info_t(), true) {
  }

}

}
