//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlLibraryBindings {

public enum ctl_vf_curve_details_t {
  CTL_VF_CURVE_DETAILS_SIMPLIFIED = 0,
  CTL_VF_CURVE_DETAILS_MEDIUM = 1,
  CTL_VF_CURVE_DETAILS_ELABORATE = 2,
  CTL_VF_CURVE_DETAILS_MAX
}

}
