//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlLibraryBindings {

public enum ctl_vf_curve_type_t {
  CTL_VF_CURVE_TYPE_STOCK = 0,
  CTL_VF_CURVE_TYPE_LIVE = 1,
  CTL_VF_CURVE_TYPE_MAX
}

}
