//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.0
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace CtlLibraryBindings {

public class ctl_os_display_encoder_identifier_t : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ctl_os_display_encoder_identifier_t(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ctl_os_display_encoder_identifier_t obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  internal static global::System.Runtime.InteropServices.HandleRef swigRelease(ctl_os_display_encoder_identifier_t obj) {
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new global::System.ApplicationException("Cannot release ownership as memory is not owned");
      global::System.Runtime.InteropServices.HandleRef ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.Dispose();
      return ptr;
    } else {
      return new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
    }
  }

  ~ctl_os_display_encoder_identifier_t() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          CtlLibraryPINVOKE.delete_ctl_os_display_encoder_identifier_t(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public uint WindowsDisplayEncoderID {
    set {
      CtlLibraryPINVOKE.ctl_os_display_encoder_identifier_t_WindowsDisplayEncoderID_set(swigCPtr, value);
    } 
    get {
      uint ret = CtlLibraryPINVOKE.ctl_os_display_encoder_identifier_t_WindowsDisplayEncoderID_get(swigCPtr);
      return ret;
    } 
  }

  public ctl_generic_void_datatype_t DisplayEncoderID {
    set {
      CtlLibraryPINVOKE.ctl_os_display_encoder_identifier_t_DisplayEncoderID_set(swigCPtr, ctl_generic_void_datatype_t.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = CtlLibraryPINVOKE.ctl_os_display_encoder_identifier_t_DisplayEncoderID_get(swigCPtr);
      ctl_generic_void_datatype_t ret = (cPtr == global::System.IntPtr.Zero) ? null : new ctl_generic_void_datatype_t(cPtr, false);
      return ret;
    } 
  }

  public ctl_os_display_encoder_identifier_t() : this(CtlLibraryPINVOKE.new_ctl_os_display_encoder_identifier_t(), true) {
  }

}

}
