//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.3.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace ADLXWrapper {

public enum ADLX_GPU_TYPE {
  GPUTYPE_UNDEFINED = 0,
  GPUTYPE_INTEGRATED,
  GPUTYPE_DISCRETE
}

}
