namespace ADLXWrapper;

public enum ADLX_MEMORYTIMING_DESCRIPTION
{
    MEMORYTIMING_DEFAULT = 0,
    MEMORYTIMING_FAST_TIMING,
    MEMORYTIMING_FAST_TIMING_LEVEL_2,
    MEMORYTIMING_AUTOMATIC,
    MEMORYTIMING_MEMORYTIMING_LEVEL_1,
    MEMORYTIMING_MEMORYTIMING_LEVEL_2,
}
