namespace ADLXWrapper;

public enum ADLX_SMARTSHIFT_ECO_INACTIVE_REASON
{
    INACTIVE_REASON_UNKNOWN = 0,
    INACTIVE_REASON_PRIMARY_DISPLAY_CONNECTED_TO_DGPU,
    INACTIVE_REASON_DETACHABLE_GPU_CONNECTED,
    INACTIVE_REASON_SESSION_INACTIVE,
    INACTIVE_REASON_MULTIPLE_SESSION_ACTIVE,
}
