namespace ADLXWrapper;

public enum ADLX_DISPLAY_TYPE
{
    DISPLAY_TYPE_UNKOWN = 0,
    DISPLAY_TYPE_MONITOR,
    DISPLAY_TYPE_TELEVISION,
    DISPLAY_TYPE_LCD_PANEL,
    DISPLAY_TYPE_DIGITAL_FLAT_PANEL,
    DISPLAY_TYPE_COMPONENT_VIDEO,
    DISPLAY_TYPE_PROJECTOR,
}
