namespace ADLXWrapper;

public enum ADLX_DP_LINK_RATE
{
    DP_LINK_RATE_UNKNOWN = 0,
    DP_LINK_RATE_RBR,
    DP_LINK_RATE_2_16GBPS,
    DP_LINK_RATE_2_43GBPS,
    DP_LINK_RATE_HBR,
    DP_LINK_RATE_4_32GBPS,
    DP_LINK_RATE_HBR2,
    DP_LINK_RATE_HBR3,
    DP_LINK_RATE_UHBR10,
    DP_LINK_RATE_UHBR13D5,
    DP_LINK_RATE_UHBR20,
}
