namespace ADLXWrapper;

public enum ADLX_GAMUT_SPACE
{
    GAMUT_SPACE_CCIR_709 = 0,
    GAMUT_SPACE_CCIR_601,
    GAMUT_SPACE_ADOBE_RGB,
    GAMUT_SPACE_CIE_RGB,
    GAMUT_SPACE_CCIR_2020,
    GAMUT_SPACE_CUSTOM,
}
