namespace ADLXWrapper;

public enum ADLX_DISPLAY_TIMING_LIMITATION
{
    PIXEL_CLOCK_MAX = 650000,
    PIXEL_CLOCK_MIN = 0,
    REFRESH_RATE_MAX = 200,
    REFRESH_RATE_MIN = 1,
    RESOLUTION_MAX = 9999,
    RESOLUTION_MIN = 1,
}
