namespace ADLXWrapper;

public enum ADLX_ORIENTATION
{
    ORIENTATION_LANDSCAPE = 0,
    ORIENTATION_PORTRAIT = 90,
    ORIENTATION_LANDSCAPE_FLIPPED = 180,
    ORIENTATION_PORTRAIT_FLIPPED = 270,
}
